name: Pipeline CI Two Ship

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  job-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Active la mise en cache ici
      - name: Installation des dépendances
        run: npm install

  job-audit:
    needs: job-build
    runs-on: ubuntu-22.04
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Récupère le cache créé par job-build
      - name: Installation des dépendances
        # Cette étape sera quasi-instantanée grâce au cache
        run: npm install
      - name: Audit des dépendances
        run: npm audit

  job-lint:
    needs: job-build
    runs-on: ubuntu-22.04
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Installation des dépendances
        run: npm install
      - name: Linter
        run: npm run lint

  job-test:
    needs: job-build
    runs-on: ubuntu-22.04
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Installation des dépendances
        run: npm install
      - name: Lancement des tests unitaires
        run: npm run test

  job-test-fonctionnel:
    needs: job-build
    runs-on: ubuntu-22.04
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installation des dépendances
        run: npm install

      - name: Lancement des tests e2e
        run: npx cypress run

      - name: Affichage du succès
        if: success()
        run: |
          echo "### Tests fonctionnels : Succès" >> $GITHUB_STEP_SUMMARY
          echo "Tous les tests fonctionnels du jeu sont validés." >> $GITHUB_STEP_SUMMARY

      - name: Capture d'écran
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: erreur-cypress
          # indique ou recuperer la capture
          path: cypress/screenshots/

  job-summary:
      needs: [job-test, job-lint, job-audit, job-test-fonctionnel]
      if: always()
      runs-on: ubuntu-22.04
      steps:
        - name: Téléchargement de la capture
          uses: actions/download-artifact@v4
          with:
            name: erreur-cypress
            path: image-recuperee
          continue-on-error: true

        - name: Génération du résumé global
          run: |
            echo "## Bilan de l'exécution" >> $GITHUB_STEP_SUMMARY
            echo "- Audit : ${{ needs.job-audit.result }}" >> $GITHUB_STEP_SUMMARY
            echo "- Linter : ${{ needs.job-lint.result }}" >> $GITHUB_STEP_SUMMARY
            echo "- Tests Unitaires : ${{ needs.job-test.result }}" >> $GITHUB_STEP_SUMMARY
            echo "- Tests Fonctionnels : ${{ needs.job-test-fonctionnel.result }}" >> $GITHUB_STEP_SUMMARY
          
            if [ -d "image-recuperee" ]; then
              echo "### Erreur de test fonctionnel" >> $GITHUB_STEP_SUMMARY
              IMAGE=$(base64 -w 0 image-recuperee/*/*.png | head -n 1)
              echo "<img src=\"data:image/png;base64,$IMAGE\" width=\"600\">" >> $GITHUB_STEP_SUMMARY
            fi